### ISSUE TITLE
Desribe why we need MetalLB IP range

### ISSUE THREAD

**Issue by NickVolynkin** [cozystack/website#118]
Get Started > [Configure Networking interconnection](https://cozystack.io/docs/get-started/#configure-networking-interconnection)

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cozystack
  namespace: cozy-metallb
spec:
  addresses:
  - 192.168.100.200-192.168.100.250
  autoAssign: true
  avoidBuggyIPs: false
```

Some readers don't understand how this range is used. It's used by the load balancer giving out external IP addresses to the k8s cluster. (External to the k8s cluster). They’re used to expose services from within Cozystack
